=== petafuel/FueliFinTS/src/main/resources/xml/xsd/fints3.0/segment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- Segment, das root Element jeder Segment - XML Datei, beihaltet beliebig viele Segmentversionen -->
    <xsd:element name="segment"
                 type="segmentType"/>


    <xsd:complexType name="segment_versionType">
        <xsd:sequence>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element type="degType" name="deg" maxOccurs="unbounded" minOccurs="0"/>
                <xsd:element type="deType" name="de" maxOccurs="unbounded" minOccurs="0"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="version"/>
    </xsd:complexType>

    <!-- Segmentversion, es kann beliebig viele Segmentversionen geben -->
    <xsd:complexType name="segmentType">
        <xsd:sequence>
            <xsd:element type="segment_versionType" name="segment_version" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="degType">
        <xsd:sequence>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element type="degType" name="deg" maxOccurs="unbounded" minOccurs="0"/>
                <xsd:element type="deType" name="de" maxOccurs="unbounded" minOccurs="0"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="element_name" use="required"/>
        <xsd:attribute type="xsd:string" name="element_alias" use="optional"/>
        <xsd:attribute type="format" name="element_format" use="optional"/>
        <xsd:attribute type="status" name="element_status" use="required"/>
        <xsd:attribute type="xsd:int" name="element_anzahl" use="required"/>
        <xsd:attribute type="xsd:string" name="element_restriktionen" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="deType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="element_name" use="required"/>
                <xsd:attribute type="xsd:string" name="element_alias" use="optional"/>
                <xsd:attribute type="format" name="element_format" use="required"/>
                <xsd:attribute type="length" name="element_laenge" use="optional"/>
                <xsd:attribute type="status" name="element_status" use="required"/>
                <xsd:attribute type="length" name="element_anzahl" use="required"/>
                <xsd:attribute type="xsd:string" name="element_restriktionen" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="typ">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="DE"/>
            <xsd:enumeration value="DEG"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="status">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="M"/>
            <xsd:enumeration value="K"/>
            <xsd:enumeration value="C"/>
            <xsd:enumeration value="O"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="format">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="an"/>
            <xsd:enumeration value="bin"/>
            <xsd:enumeration value="btg"/>
            <xsd:enumeration value="code"/>
            <xsd:enumeration value="cur"/>
            <xsd:enumeration value="dat"/>
            <xsd:enumeration value="dig"/>
            <xsd:enumeration value="dta"/>
            <xsd:enumeration value="id"/>
            <xsd:enumeration value="jn"/>
            <xsd:enumeration value="kik"/>
            <xsd:enumeration value="kti"/>
            <xsd:enumeration value="ktv"/>
            <xsd:enumeration value="num"/>
            <xsd:enumeration value="tim"/>
            <xsd:enumeration value="tsp"/>
            <xsd:enumeration value="ctr"/>
            <xsd:enumeration value="sdo"/>
            <xsd:enumeration value="null"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="length">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\.{0,2}[0-9]+"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hikim.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="2">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>
        <de element_name="Betreff"
            element_format="an"
            element_laenge="..35"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Freitextmeldung"
            element_format="txt"
            element_laenge="..2048"
            element_status="M"
            element_anzahl="1"/>
    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hissp.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="3">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>
        <de element_name="Nachrichtenbeziehung, kodiert"
            element_format="code"
            element_laenge="1"
            element_status="M"
            element_anzahl="1"
            element_restriktionen="1"/>

        <de element_name="Austauschkontrollreferenz"
            element_format="id"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Nachrichtenrefernznummer"
            element_format="num"
            element_laenge="..4"
            element_status="M"
            element_anzahl="1"
            element_restriktionen=">0"/>

        <de element_name="Bezeichner für Funktionstyp"
            element_format="code"
            element_laenge="..3"
            element_status="M"
            element_anzahl="1"
            element_restriktionen="231"/>

        <deg element_name="Schlüsselname"
             element_status="M"
             element_anzahl="1">
            <deg element_name="Kreditinstituteskennung" element_format="kik" element_status="M"
                 element_anzahl="1"/>
            <de element_name="Benutzerkennung" element_format="id" element_status="M"
                element_anzahl="1"/>
            <de element_name="Schlüsselart" element_format="code" element_laenge="1" element_status="M"
                element_anzahl="1" element_restriktionen="D, S, V"/>
            <de element_name="Schlüsselnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Schlüsselnummer" element_format="num" element_status="M"
                element_anzahl="1"/>
        </deg>

        <de element_name="Sperrenkennzeichen"
            element_format="code"
            element_laenge="..3"
            element_status="M"
            element_anzahl="1"
            element_restriktionen="1, 501, 999"/>

        <deg element_name="Sicherheitsdatum und -uhrzeit"
             element_status="M"
             element_anzahl="1">
            <de element_name="Datum- und Zeitbezeichner, kodiert" element_format="code" element_laenge="..3" element_status="M"
                element_anzahl="1" element_restriktionen="1, 6"/>
            <de element_name="Datum" element_format="dat" element_status="O"
                element_anzahl="1"/>
            <de element_name="Uhrzeit" element_format="tim"  element_status="C"
                element_anzahl="1" element_restriktionen="O: ‚Datum’ belegt N: sonst"/>
        </deg>

        <deg element_name="Zertifikat"
             element_status="O"
             element_anzahl="1">

            <de element_name="Zertifikatstyp" element_format="code" element_laenge="1" element_status="M"
                element_anzahl="1" element_restriktionen="1, 2, 3"/>
            <de element_name="Zertifikatsinhalt" element_format="bin" element_laenge="..4096" element_status="M"
                element_anzahl="1"/>
        </deg>
    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hikpv.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="1">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>

        <deg element_name="UnterstÃ¼tzte Komprimierungsverfahren"
             element_status="M"
             element_anzahl="1..9">
            <de element_name="Komprimierungsfunktion" element_format="code" element_laenge="..3" element_status="M"
                element_anzahl="1" element_restriktionen="0,1,2,3,4,5,6,7,999"/>
            <de element_name="Komprimierungsversion" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="..9"/>
        </deg>
    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hibpa.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="3">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>

        <de element_name="BPD-Version"
            element_format="num"
            element_laenge="..3"
            element_status="M"
            element_anzahl="1"/>

        <deg element_name="Kreditinstitutskennung"
            element_format="kik"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Kreditinstitutsbezeichnung"
            element_format="an"
            element_laenge="..60"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Anzahl Geschäftsvorfälle"
            element_format="num"
            element_laenge="..3"
            element_status="M"
            element_anzahl="1"/>

        <deg element_name="Unterstütze Sprachen"
             element_status="M"
             element_anzahl="1">
            <de element_name="Unterstütze Sprachen" element_format="code" element_laenge="..3" element_status="M"
                element_anzahl="..9" element_restriktionen="1, 2, 3"/>
        </deg>

        <deg element_name="Unterstütze HBCI-Versionen"
             element_status="M"
             element_anzahl="1">
            <de element_name="Unterstütze HBCI-Versionen" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="..9"/>
        </deg>

        <de element_name="Maximale Nachrichtengröße"
            element_format="num"
            element_laenge="..4"
            element_status="O"
            element_anzahl="1"/>

        <de element_name="Minimaler Timeout-Wert"
            element_format="num"
            element_laenge="..4"
            element_status="O"
            element_anzahl="1"/>

        <de element_name="Maximaler Timeout-Wert"
            element_format="num"
            element_laenge="..4"
            element_status="O"
            element_anzahl="1"/>
    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hiupd.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="6">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>

        <deg element_name="Kontoverbindung"
             element_status="C"
             element_anzahl="1"
             element_format="ktv"
             element_restriktionen="N: bei Geschäftsvorfällen ohne Kontenbezug M: sonst"/>

        <de element_name="IBAN"
            element_format="an"
            element_laenge="..34"
            element_status="O"
            element_anzahl="1"/>

        <de element_name="Kunden-ID"
            element_format="id"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Kontoart"
            element_format="num"
            element_laenge="..2"
            element_status="O"
            element_anzahl="1"/>

        <de element_name="Kontowährung"
            element_format="cur"
            element_status="O"
            element_anzahl="1"/>

        <de element_name="Name des Kontoinhabers 1"
            element_format="an"
            element_laenge="..27"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Name des Kontoinhabers 2"
            element_format="an"
            element_laenge="..27"
            element_status="O"
            element_anzahl="1"/>

        <de element_name="Kontoproduktbezeichnung"
            element_format="num"
            element_laenge="..30"
            element_status="O"
            element_anzahl="1"/>

        <deg element_name="Kontolimit"
             element_status="K"
             element_anzahl="1">
            <de element_name="Limitart" element_format="code" element_laenge="1" element_status="M"
                element_anzahl="1" element_restriktionen="E,T,W,M,Z"/>
            <deg element_name="Limitbetrag" element_format="btg" element_status="C"
                 element_anzahl="1" element_restriktionen=" O: Limitart Z N: sonst"/>
            <de element_name="Limit-Tage" element_format="num" element_laenge="..3" element_status="C"
                element_anzahl="1" element_restriktionen="0 O: Limitart = Z N: sonst"/>
        </deg>

        <deg element_name="Erlaubte Geschäftsvorfälle"
             element_status="K"
             element_anzahl="999">
            <de element_name="Geschäftsvorfall" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Anzahl benötigter Signaturen" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1" element_restriktionen="0,1,2,3"/>
            <de element_name="Limitart" element_format="code" element_laenge="1" element_status="M"
                element_anzahl="1" element_restriktionen="E,T,W,M,Z"/>
            <deg element_name="Limitbetrag" element_format="btg" element_status="C"
                 element_anzahl="1" element_restriktionen=" O: Limitart Z N: sonst"/>
            <de element_name="Limit-Tage" element_format="num" element_laenge="..3" element_status="C"
                element_anzahl="1" element_restriktionen="0 O: Limitart = Z N: sonst"/>
        </deg>

        <de element_name="Erweiterung, kontobezogen"
            element_format="an"
            element_laenge="..2048"
            element_status="O"
            element_anzahl="1"/>
    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hkidn.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="2">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>

        <deg element_name="Kreditinstituteskennung" element_format="kik" element_status="M"
             element_anzahl="1"/>

        <de element_name="Kunden-ID"
            element_format="id"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Kundensystem-ID"
            element_format="id"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Kundensystem-Status"
            element_format="code"
            element_laenge="1"
            element_status="M"
            element_anzahl="1"
            element_restriktionen="0,1"/>

    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hkisa.xml
<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="3">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>

        <de element_name="Nachrichtenbeziehung"
            element_format="code"
            element_laenge="1"
            element_status="M"
            element_anzahl="1"
            element_restriktionen="2"/>

        <de element_name="Bezeichner für Funktionstyp"
            element_format="code"
            element_laenge="..3"
            element_status="M"
            element_anzahl="1"
            element_restriktionen="124"/>

        <deg element_name="Sicherheitsprofil"
             element_status="M"
             element_anzahl="1">
            <de element_name="Sicherheitsverfahren,Code" element_format="code" element_laenge="3" element_status="M"
                element_anzahl="1" element_restriktionen="DDV, RAH, RDH, PIN, EMV"/>
            <de element_name="Version des Sicherheitsverfahrens" element_format="num" element_laenge="..3"
                element_status="M"
                element_anzahl="1" element_restriktionen="1, 2, 3, 4, 5, 6, 7, 8, 9, 10"/>
        </deg>

        <deg element_name="Schlüsselname"
             element_status="M"
             element_anzahl="1">
            <deg element_name="Kreditinstituteskennung" element_format="kik" element_status="M"
                 element_anzahl="1"/>
            <de element_name="Benutzerkennung" element_format="id" element_status="M"
                element_anzahl="1"/>
            <de element_name="Schlüsselart" element_format="code" element_laenge="1" element_status="M"
                element_anzahl="1" element_restriktionen="D, S, V"/>
            <de element_name="Schlüsselnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Schlüsselnummer" element_format="num" element_status="M"
                element_anzahl="1"/>
        </deg>

        <deg element_name="Zertifikat"
             element_status="O"
             element_anzahl="1">

            <de element_name="Zertifikatstyp" element_format="code" element_laenge="1" element_status="M"
                element_anzahl="1" element_restriktionen="1, 2, 3"/>
            <de element_name="Zertifikatsinhalt" element_format="bin" element_laenge="..4096" element_status="M"
                element_anzahl="1"/>
        </deg>
    </segment_version>
</segment>

=== petafuel/FueliFinTS/src/main/resources/xml/fints3.0/hnhbk.xml
<?xml version="1.0" encoding="UTF-8"?>

<segment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fints3.0/segment.xsd">

    <segment_version version="3">
        <deg element_name="Segmentkopf"
             element_anzahl="1"
             element_status="M">
            <de element_name="Segmentname" element_format="an" element_laenge="..6" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentnummer" element_format="num" element_laenge="..3" element_status="M"
                element_anzahl="1"/>
            <de element_name="Segmentversion" element_format="num" element_laenge="..2" element_status="M"
                element_anzahl="1"/>
        </deg>
        <de element_name="Nachrichtengröße"
            element_format="dig"
            element_laenge="12"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="HBCI-Version"
            element_format="num"
            element_laenge="..3"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Dialog-ID"
            element_format="id"
            element_status="M"
            element_anzahl="1"/>

        <de element_name="Nachrichtennummer"
            element_format="null"
            element_laenge="..4"
            element_status="M"
            element_anzahl="1"
            element_restriktionen=">0"/>
        <deg element_name="Bezugsnachricht"
             element_status="K"
             element_anzahl="1">
            <de element_name="Dialog-ID" element_format="id" element_laenge="0" element_status="M"
                element_anzahl="1"/>
            <de element_name="Nachrichtennummer" element_format="num" element_laenge="..4" element_status="M"
                element_anzahl="1"/>
        </deg>
    </segment_version>
</segment>
